version: 2
updates:
  - &defaults
    package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns: [ "*" ]
    cooldown:
      default-days: 3

  - <<: *defaults
    package-ecosystem: npm
    directory: /dashboard

  - <<: *defaults
    package-ecosystem: github-actions

  - <<: *defaults
    package-ecosystem: docker
